pass CIDR on to tests

diff --git a/upload/common/getoption b/upload/common/getoption
--- a/upload/common/getoption
+++ b/upload/common/getoption
@@ -112,6 +112,15 @@ while [[ $# > 0 ]]; do
                 exit 1
             fi
             ;;
+        --ipcidr)       # Takes an option argument, ensuring it has been specified.
+            if [ -n "$2" ]; then
+                PRIVATEIPCIDR=$2
+                shift
+            else
+                printf 'ERROR: "--iprange" requires a non-empty option argument.\n' >&2
+                exit 1
+            fi
+            ;;
 
         *)               # Default case: If no more options then break out of the loop.
             ;;
