Explicitly pass the correct test units

diff --git a/upload/common/getoption b/upload/common/getoption
--- a/upload/common/getoption
+++ b/upload/common/getoption
@@ -121,6 +121,15 @@ while [[ $# > 0 ]]; do
                 exit 1
             fi
             ;;
+        --units)       # Takes an option argument, ensuring it has been specified.
+            if [ -n "$2" ]; then
+                TESTUNITS=$2
+                shift
+            else
+                printf 'ERROR: "--units" requires a non-empty option argument.\n' >&2
+                exit 1
+            fi
+            ;;
 
         *)               # Default case: If no more options then break out of the loop.
             ;;
